---

- name: Install EPEL repository
  ansible.builtin.package:
    name: epel-release
    state: present
  become: true
  tags: [fail2ban, packages]  # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882

...
